# Generated by Django 3.1.4 on 2022-05-02 20:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lottery",
            fields=[
                ("lotery_nb", models.AutoField(primary_key=True, serialize=False)),
                ("lotery_name", models.CharField(default="Lottery", max_length=255)),
                ("lotery_address", models.CharField(default="0xfasdf", max_length=255)),
                ("date_start", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_end", models.DateTimeField(default=django.utils.timezone.now)),
                ("duration", models.IntegerField(default=7)),
                ("ticket_price", models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.IntegerField(default=1)),
                ("gain", models.CharField(max_length=255)),
                (
                    "lotery_nb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="lottery.lottery",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_holder_wallet_address", models.CharField(max_length=128)),
                ("date_start", models.DateTimeField(default=django.utils.timezone.now)),
                ("transation_id", models.CharField(max_length=128)),
                (
                    "lotery_nb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="lottery.lottery",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Winner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lotery_nb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winner",
                        to="lottery.lottery",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winner",
                        to="lottery.price",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winner",
                        to="lottery.ticket",
                    ),
                ),
            ],
        ),
    ]
