# Generated by Django 3.1.4 on 2022-05-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lottery",
            old_name="lotery_address",
            new_name="lotery_wallet_address",
        ),
    ]
