# Generated by Django 3.1.4 on 2022-05-03 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0002_auto_20220503_0154"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="date_start",
            new_name="date",
        ),
    ]
