# Generated by Django 3.1.4 on 2022-05-03 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0003_auto_20220503_0224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winner",
            name="lotery_nb",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winners",
                to="lottery.lottery",
            ),
        ),
        migrations.AlterField(
            model_name="winner",
            name="price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winners",
                to="lottery.price",
            ),
        ),
        migrations.AlterField(
            model_name="winner",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winners",
                to="lottery.ticket",
            ),
        ),
    ]
