# Generated by Django 3.1.4 on 2022-05-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0004_auto_20220503_0239"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("content", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="lottery",
            name="cashin_display",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_nb",
            field=models.IntegerField(default=10),
        ),
    ]
