# Generated by Django 4.0 on 2022-05-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0005_auto_20220504_0908"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lottery",
            name="ticket_price",
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name="price",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="trad",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="trad",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="winner",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
