version: '3.8'

services:
  # front:
  #   build: ./front
  #   volumes:
  #     - ./front:/front
  #   command: node build
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - back
  # back:
  #   build: ./back
  #   volumes:
  #     - ./back:/back
  #   command: gunicorn back.wsgi:application --bind 0.0.0.0:8000
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./back/.env
  #   depends_on:
  #     - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres_data/.env

volumes:
  volumes:
