version: '3.8'

services:
  front:
    build: ./front
    command: node build
    ports:
      - 3000:3000
    env_file:
      - ./front/.env
    depends_on:
      - back
  back:
    build: ./back
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./back/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data: